Upload/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Upload.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Upload/Pages/FileList.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using Upload.Data;
using Upload.Models;

namespace Upload.Pages
{
    public class FileListModel : PageModel
    {
        private readonly UploadContext _context;

        public FileListModel(UploadContext context)
        {
            _context = context;
        }

        public IList<AppFile> DatabaseFiles { get; private set; }

        public async Task OnGetAsync()
        {
            DatabaseFiles = await _context.File.Where(f => f.Size < 2000).AsNoTracking().ToListAsync();
        }

        public async Task<IActionResult> OnGetDownloadDbAsync(int? id)
        {
            if (id == null)
            {
                return Page();
            }

            var requestFile = await _context.File.SingleOrDefaultAsync(m => m.Id == id);

            if (requestFile == null)
            {
                return Page();
            }

            // Don't display the untrusted file name in the UI. HTML-encode the value.
            return File(requestFile.Content, MediaTypeNames.Application.Octet, WebUtility.HtmlEncode(requestFile.UntrustedName));
        }
    }
}

Upload/Pages/FileUpload.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Upload.Data;
using Upload.Models;
using Upload.Utilities;

namespace Upload.Pages
{
    public class FileUploadModel : PageModel
    {
        private readonly UploadContext _context;
        private readonly long _fileSizeLimit;
        private readonly string[] _permittedExtensions = { ".txt" };

        public FileUploadModel(UploadContext context,
            IConfiguration config)
        {
            _context = context;
            _fileSizeLimit = config.GetValue<long>("FileSizeLimit");
        }

        [BindProperty]
        public FileUpload FileUpload { get; set; }

        public string Result { get; private set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostUploadAsync()
        {
            // Perform an initial check to catch FileUpload class
            // attribute violations.
            if (!ModelState.IsValid)
            {
                Result = "Please correct the form.";

                return Page();
            }

            foreach (var formFile in FileUpload.FormFiles)
            {
                var formFileContent =
                    await FileHelpers.ProcessFormFile<FileUpload>(
                        formFile, ModelState, _permittedExtensions,
                        _fileSizeLimit);

                // Perform a second check to catch ProcessFormFile method
                // violations. If any validation check fails, return to the
                // page.
                if (!ModelState.IsValid)
                {
                    Result = "Please correct the form.";

                    return Page();
                }

                // **WARNING!**
                // In the following example, the file is saved without
                // scanning the file's contents. In most production
                // scenarios, an anti-virus/anti-malware scanner API
                // is used on the file before making the file available
                // for download or for use by other systems. 
                // For more information, see the topic that accompanies 
                // this sample.

                var file = new AppFile()
                {
                    Content = formFileContent,
                    UntrustedName = formFile.FileName,
                    Note = FileUpload.Note,
                    Size = formFile.Length,
                    UploadDT = DateTime.UtcNow
                };

                _context.File.Add(file);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./FileList");
        }
    }

    public class FileUpload
    {
        [Required]
        [Display(Name = "File")]
        public List<IFormFile> FormFiles { get; set; }

        [Display(Name = "Note")]
        [StringLength(50, MinimumLength = 0)]
        public string Note { get; set; }
    }
}

Upload/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Upload.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Upload/Pages/LargeFileUpload.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Upload
{
    public class LargeFileUploadDbModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Upload/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Upload.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Upload/Pages/FileList.cshtml
@page
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model Upload.Pages.FileListModel
@{
    ViewData["Title"] = "File List";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>File List (files less than 2 Mb)</h1>
@if (SignInManager.IsSignedIn(User))
{
    @if (Model.DatabaseFiles.Count == 0)
    {
        <p>
            No files are available. 
        </p>
    }
    else
    {
        <table>
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.DatabaseFiles[0].UntrustedName)
                    </th>
                    <th>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DatabaseFiles[0].UploadDT)
                    </th>
                    <th>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DatabaseFiles[0].Size)
                    </th>
                    <th>
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var file in Model.DatabaseFiles)
                {
                    <tr>
                        <td>
                            <b>@file.UntrustedName</b><br>
                        </td>
                        <td class="text-center">
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => file.UploadDT)
                        </td>
                        <td class="text-center">
                        </td>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => file.Size)
                        </td>
                        <td class="text-center">
                        </td>
                        <td class="text-center">
                            <a asp-page-handler="DownloadDb" asp-route-id="@file.Id">Download</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

Upload/Pages/FileUpload.cshtml
@page
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model Upload.Pages.FileUploadModel
@{
    ViewData["Title"] = "FileUpload";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@if (SignInManager.IsSignedIn(User))
{
    <h1>File Upload</h1>


    <form enctype="multipart/form-data" method="post">
        <dl>
            <dt>
                <label asp-for="FileUpload.Note"></label>
            </dt>
            <dd>
                <input asp-for="FileUpload.Note" type="text" />
                <span asp-validation-for="FileUpload.Note"></span>
            </dd>
            <dt>
                <label asp-for="FileUpload.FormFiles"></label>
            </dt>
            <dd>
                <input asp-for="FileUpload.FormFiles" type="file" multiple />
                <span asp-validation-for="FileUpload.FormFiles"></span>
            </dd>
        </dl>
        <input asp-page-handler="Upload" class="btn btn-primary" type="submit" value="Upload" />
    </form>

    <p class="result">
        @Model.Result
    </p>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
}

Upload/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4"></h1>
</div>

Upload/Pages/LargeFileUpload.cshtml
@page
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model LargeFileUploadDbModel
@{
    ViewData["Title"] = "Large File Upload";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@if (SignInManager.IsSignedIn(User))
{
    <h1>Large File Upload</h1>

    <form id="uploadForm" action="Streaming/UploadDatabase" method="post" 
        enctype="multipart/form-data" onsubmit="AJAXSubmit(this);return false;">
        <dl>
            <dt>
                <label for="note">Note</label>
            </dt>
            <dd>
                <input id="note" type="text" name="note"  />
            </dd>
            <dt>
                <label for="file">File</label>
            </dt>
            <dd>
                <input id="file" type="file" name="file" />
            </dd>
        </dl>

        <input class="btn btn-primary" type="submit" value="Upload" />

        <div style="margin-top:15px">
            <output form="uploadForm" name="result"></output>
        </div>
    </form>

    @section Scripts {
      <script>
        "use strict";

        async function AJAXSubmit (oFormElement) {
          const formData = new FormData(oFormElement);

          try {
            const response = await fetch(oFormElement.action, {
              method: 'POST',
              headers: {
                'RequestVerificationToken': getCookie('RequestVerificationToken')
              },
              body: formData
            });

            oFormElement.elements.namedItem("result").value = 
              'Result: ' + response.status + ' ' + response.statusText;
          } catch (error) {
            console.error('Error:', error);
          }
        }

        function getCookie (name) {
          var value = "; " + document.cookie;
          var parts = value.split("; " + name + "=");
          if (parts.length == 2) return parts.pop().split(";").shift();
        }
      </script>
    }

}